// <auto-generated />
using System;
using AdamSarok.BoincStatsFunctionApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoincStatsFunctionApp.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    partial class StatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Common.Models.HostStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("HostName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("float");

                    b.HasKey("YYYYMMDD", "HostName");

                    b.ToTable("HostStats");
                });

            modelBuilder.Entity("Common.Models.ProjectStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("float");

                    b.HasKey("YYYYMMDD", "ProjectName");

                    b.ToTable("ProjectStats");
                });
#pragma warning restore 612, 618
        }
    }
}
