// <auto-generated />
using System;
using BoincWatchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoincWatcherService.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20260117105252_ProjectMapping")]
    partial class ProjectMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoincWatcherService.Models.HostStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("HostName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("double precision");

                    b.HasKey("YYYYMMDD", "HostName");

                    b.ToTable("HostStats");
                });

            modelBuilder.Entity("BoincWatcherService.Models.ProjectMap", b =>
                {
                    b.Property<string>("MasterUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("MasterUrl");

                    b.ToTable("ProjectMaps");
                });

            modelBuilder.Entity("BoincWatcherService.Models.ProjectStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MasterUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("double precision");

                    b.HasKey("YYYYMMDD", "ProjectId");

                    b.ToTable("ProjectStats2", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
