// <auto-generated />
using System;
using BoincWatchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoincWatcherService.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    [Migration("20260124221056_BoincTasks")]
    partial class BoincTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoincWatcherService.Models.BoincTask", b =>
                {
                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .HasColumnType("text");

                    b.Property<string>("HostName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectName", "TaskName", "HostName");

                    b.ToTable("BoincTasks");
                });

            modelBuilder.Entity("BoincWatcherService.Models.HostProjectStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("HostName")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("YYYYMMDD", "HostName", "ProjectName");

                    b.ToTable("HostProjectStats");
                });

            modelBuilder.Entity("BoincWatcherService.Models.HostStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("HostName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("YYYYMMDD", "HostName");

                    b.ToTable("HostStats");
                });

            modelBuilder.Entity("BoincWatcherService.Models.ProjectStats", b =>
                {
                    b.Property<string>("YYYYMMDD")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LatestTaskDownloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalCredit")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("YYYYMMDD", "ProjectName");

                    b.ToTable("ProjectStats");
                });
#pragma warning restore 612, 618
        }
    }
}
